### ISSUE TITLE
Support additional watch models.

### ISSUE THREAD

**Issue by Cralex** [mattrossman/forecaswatch2#11]
It would be nice if this could support more watch models in the future. I understand that it would be hard to change the layout for the Pebble Round, but it should be possible to make a grayscale version to support the Original and Steel models. (My pebble 2 isn’t working right now, so I can’t tell if it is currently supported or not.)

**Comment by mattrossman** [comment]
How does this look?
![bw_composite](https://user-images.githubusercontent.com/22670878/65000055-2d790a00-d8b8-11e9-97eb-f4c78ba618f9.png)

I've never used one of the B&W Pebbles before so I'm not sure what the best practices for coloring are. I figure I'd leave the battery white all the time, the only gray-ish color would be the shading under the precipitation chart.

**Comment by Cralex** [comment]
Looks great to me! I’d use that on my Pebble Steel for sure.

**Comment by mattrossman** [comment]
@Cralex check out the [v1.1.0](https://github.com/mattrossman/forecaswatch2/releases/tag/v1.1.0) release and let me know if that works for you.

**Comment by Cralex** [comment]
Looks really nice on my Pebble Steel!
