### ISSUE TITLE
Make AM/PM option for time in x-axis. 

### ISSUE THREAD

**Issue by mmckeever23** [mattrossman/forecaswatch2#13]

**Comment by mattrossman** [comment]
@mmckeever23  Do you want to text 'AM' and 'PM' to actually show up along the axis, or just have the option to set 12 hour / 24 hour time for the hour values? There's not much space down there for more text.

**Comment by mmckeever23** [comment]
Doesn't need to say AM and PM, just 12 hour time values. Thank you!

Matt McKeever
Musician, Educator, Composer
mckeevermusic.weebly.com [http://www.mckeevermusic.weebly.com/]
On 9/21/2019 9:28:20 AM, Matt Rossman <notifications@github.com> wrote:
@mmckeever23 [https://github.com/mmckeever23] Do you want to text 'AM' and 'PM' to actually show up along the axis, or just have the option to set 12 hour / 24 hour time for the hour values? There's not much space down there for more text.

**Comment by shadow303** [comment]
Could be just like "6p" or "8a" for simplicity.

**Comment by mattrossman** [comment]
Included in v1.4.0

**Comment by mmckeever23** [comment]
Thank you!

Matt McKeever
Musician, Educator, Composer
mckeevermusic.weebly.com [http://www.mckeevermusic.weebly.com/]
On 10/5/2019 12:19:45 PM, Matt Rossman <notifications@github.com> wrote:
Included in v1.4.0
