### ISSUE TITLE
Add 24h support for time display

### ISSUE THREAD

**Issue by shadow303** [mattrossman/forecaswatch2#15]
Ok, first thing first, being able to read the time in 24h format could be really useful for all of us metric guys ))

**Comment by mattrossman** [comment]
Sure thing, for now I'll make it dependent on what you have in the watch settings. Busy with school work at the moment but I expect to knock out all the time format issues within the week.

**Comment by mattrossman** [comment]
Included in v1.4.0

**Comment by shadow303** [comment]
also could you have a look at the Rise/sunset times. They are given in 12h format but without the AP/PM identification

**Comment by mattrossman** [comment]
Moving that over to #16
