### ISSUE TITLE
Add 24h format for sunrise/sunset time

### ISSUE THREAD

**Issue by mattrossman** [mattrossman/forecaswatch2#16]

**Comment by mattrossman** [comment]
@shadow303 Is it alright if the format uses the 12/24h setting in the watch, like the main time does?

**Comment by shadow303** [comment]
I think so. 24H/12H toggle should be global for all the numbers in the watchface: main time, sunset, weather graph, first day of the week. (witch is usually Monday for metric countries but could be a separate setting on its own).
Can not speak for all the 12h users here, but I think adding A or P for the sunset/rise time could also make sense: like 6:35A and 7:12P instead 6:35AM and 7:12PM

**Comment by mattrossman** [comment]
I want to keep the weather graph format separate, since I'm a 12h user but I prefer 24h labels on the graph (at least, until I add some kind of visual day/night distinction).

I'm wary to add more characters to the sun times--for longer city names, the space in that line definitely gets cramped. I guess I'm lucky as a 12h user, the times always work out to 3 digits; 24h users will have to deal with that extra character for sunsets regardless.

Most clocks I look at (e.g. in Android) do away with the AM/PM without much confusion. I'm also not sure it would add useful info to the existing arrow; sunset will always say 'P', and sunrise will always say 'A'.

My plan for now is to have the sun events time mirror the formatting of the main time, just plain 12/24h time digits. If the ambiguity continues to be a problem you can open another issue to expand the formatting options.

**Comment by shadow303** [comment]
>  sunset will always say 'P', and sunrise will always say 'A'.
> 

I guess it makes sense.

> My plan for now is to have the sun events time mirror the formatting of the main time, just plain 12/24h time digits. If the ambiguity continues to be a problem you can open another issue to expand the formatting options.
I think one master 24h switch for the whole watchface is OK. 
If you feel you don`t have enough symbols for the longer city names you could just shave them off by a couple of letters: "_+7__Riverside Vill_17:59|_" after all the cityname is just there so you would know you`re getting the proper weather forecast for your region.

**Comment by mattrossman** [comment]
Included in v1.5.0
