### ISSUE TITLE
Date selector color should be more visible

### ISSUE THREAD

**Issue by shadow303** [mattrossman/forecaswatch2#17]
Current date cursor in the calendar on Basalt should be changed to a more contrast color like for example the blue perspiration color on the weather graph. Right now the dark blue is almost indistinguishable form the black background, unless the watch is in the direct sunlight or with back-light on. Or make it a black number against the white rectangle as it was in the original Forecastwatch.

**Comment by mattrossman** [comment]
I'll add a color picker for color models so you can make it anything you want 🌈

**Comment by mattrossman** [comment]
Included in v1.5.0
