### ISSUE TITLE
Option to change clock font to LECO

### ISSUE THREAD

**Issue by arcaderaid** [mattrossman/forecaswatch2#24]
LECO is a Pebble system font. It would be great to change the time to the largest possible LECO font that would fit into that area.

**Comment by mattrossman** [comment]
![screenshot](https://i.imgur.com/mPRlz4L.png)

Implemented on develop, will be included in next release.

**Comment by arcaderaid** [comment]
This is great!  Is there a schedule for next release?

**Comment by mattrossman** [comment]
I can merge it in for a release today or tomorrow, I just want to finish one more feature (#26) first. 

Sorry it took so long to get to these issues, the past month was hell with final projects and grad school applications.

**Comment by arcaderaid** [comment]
No problem at all.  I'm just glad you're developing the watch face in the first place.  Thanks!

**Comment by mattrossman** [comment]
v1.9.0 is published (I'll get to that vibrate on disconnect feature later).
