### ISSUE TITLE
Vibrate on connect/disconnect

### ISSUE THREAD

**Issue by a-krayushkin** [mattrossman/forecaswatch2#26]
Vibrate on connect/disconnect and show Bluetooth icon

**Comment by mattrossman** [comment]
@a-krayushkin Do you want an icon to be always present? How about showing one just when bluetooth is disconnected?

**Comment by mattrossman** [comment]
Also in the config page I'm thinking this could be two separate features. One for "Show bluetooth indicator" and one for "Vibrate on disconnect"

**Comment by arcaderaid** [comment]
To add onto https://github.com/mattrossman/forecaswatch2/issues/22 , it would be nice if this icon could change to show Bluetooth disconnected, Bluetooth connected, Quiet time enabled such as from NineTime:

![7AAC0990-87D0-4848-B3FC-9430FD493B63](https://user-images.githubusercontent.com/32489248/71562456-516af080-2a4e-11ea-8966-6767b8c4aeeb.gif)

**Comment by mattrossman** [comment]
Does that convey the case when the phone is disconnected and quiet time is active? I think calendar events can still buzz without a connection.

My thought is having independent icons like this:

![](https://i.imgur.com/R2CQbTd.png) ![](https://i.imgur.com/6vzT2XX.png)

And in settings, toggles for:

* Show quiet time
* Show bluetooth connected
* Show bluetooth disconnected
* Vibrate on disconnect

(Personally I would only want the quiet time and bluetooth disconnect indicators activated)

**Comment by arcaderaid** [comment]
Since you'd show both icons independently, your scenario looks good to me.

**Comment by mattrossman** [comment]
Added in v1.10.0
