### ISSUE TITLE
Clock in 24-hour format

### ISSUE THREAD

**Issue by Stan-Tastic** [mattrossman/forecaswatch2#27]
I am used to 24-hour current time format, would it be possible to implement a switch for that?

**Comment by mattrossman** [comment]
Right now the time format is controlled by the watch settings, not the watchface ones.
Go to Settings > Date & Time > Time Format and click to switch to 24h, then you will see the current time in 24-hour format.

**Comment by mattrossman** [comment]
I added a tip in the v1.10.0 config page to make this more clear.

**Comment by Stan-Tastic** [comment]
<facepalm> of course it is, not sure what I was thinking...
