### ISSUE TITLE
Please add AM/PM next to time.

### ISSUE THREAD

**Issue by armistry586** [mattrossman/forecaswatch2#32]

**Comment by mattrossman** [comment]
What do you think would be the best way to design this? Currently the time takes up pretty much the full screen width when it's 4-digits (e.g. 12:30). 

![4 digit time](https://i.imgur.com/n5ejuqr.png)

Also, certain [fonts](https://developer.rebble.io/developer.pebble.com/guides/app-resources/system-fonts/index.html) have limited support for alphabet characters. Leco only supports AM/PM at size 26 and the default Roboto font supports it at size 21. For reference, the calendar digits use Gothic 18 and it looks like I could barely squeeze in two of those characters next to a 4-digit time.

One option could be to use some fixed font to add a small "P" or "M" next to the time.

![roboto with p](https://i.imgur.com/XCVlDgj.png)

Which may look a little funny for different fonts

![leco with p](https://i.imgur.com/eYNNo8x.png)

**Comment by armistry586** [comment]
What if you push the time all the way to left margin? This will make space for AM/PM to fit on the right side of time. I like your idea of fixed font to add AM/PM rather than just P/M.

**Comment by mattrossman** [comment]
Here is what that might look like

![time left aligned](https://i.imgur.com/PTQ1Y75.png)

What do you think?

**Comment by armistry586** [comment]
Looks great! Please release this.

**Comment by mattrossman** [comment]
Note that it's just a photo mockup. I will work on implementing it but it takes a while to work out all the spacing bugs for edge cases. I also found a memory issue that I'm trying to resolve.

**Comment by mattrossman** [comment]
Implemented in v1.12.0

**Comment by mattrossman** [comment]
Marking v1.12.0 as pre-release because it introduces an overflow bug to the main time.
