### ISSUE TITLE
Add red color to Sunday column?

### ISSUE THREAD

**Issue by armistry586** [mattrossman/forecaswatch2#35]
Just like old Forecasweather face can you add red color to Sunday column fonts? It's easier to know the day when you glance the watchface.

**Comment by mattrossman** [comment]
Added in [v1.15.0](https://github.com/mattrossman/forecaswatch2/releases/tag/v1.15.0), you can set the Sunday column to any color you like.

**Comment by arromdee** [comment]
Not sure exactly where to put this...  but looking at the code it looks like 1.15.0 fails to exclude the holiday from being colored on its normal day when it gets colored on a Monday or Friday.

**Comment by mattrossman** [comment]
Ah true, I misunderstood the intent of that part of the switch statement when I was reformatting. I'll add a line to ensure `is_us_federal_holiday` returns false for weekends.

**Comment by mattrossman** [comment]
Updated in v1.16.0
