### ISSUE TITLE
gif animation on wrist flick

### ISSUE THREAD

**Issue by Julpebble** [mattrossman/forecaswatch2#48]
Hi there! 
Hope you are well ! Actually I would love to get an animation (gif) from a flick. Forecaster remains all the time on the pebble like it is right now, and a wrist flick triggers the little animation for a few seconds.  Maybe we can even have a custom gif. If this possible, it would be just amazing! Take care

**Comment by Julpebble** [comment]
PS: I run Pebble 2 and plan to keep using it for years. Any help for a little animation trigger will be amazing! Take care pebble lovers!

**Comment by mattrossman** [comment]
Out of scope, thanks for the suggestion though
