### ISSUE TITLE
Weatherunserground not syncing 

### ISSUE THREAD

**Issue by tuxianerDE** [mattrossman/forecaswatch2#53]
Hi,

First and foremost love the watchface and use it as a daily driver. Since yesterday night 10:30 PM CEST weatherunserground data are not synced anymore.

I wonder if I am the only one who has the issue or if something changed at least the service does not seem to be down.

I am using GPS location settings however also a fixed location is not working.

Any hint/additional info highly appreciated would not want to change my beloved watchface :)

Cheers and happy Easter

**Comment by lstarritt** [comment]
Hi, 
I have been having this same issue. I also use it as my daily driver. It is definitely possible Weather Underground fixed whatever hacky workaround was being used to get weather data, though I have no evidence of this.

**Comment by zcross24** [comment]
Hi, 
I am also having this same issue. This watchface has been a big reason for my continued use of my Pebble 2. It's good to know there are others out there who use and love this watchface as much as I do. Hope we can get this resolved. 
Happy Easter :)

**Comment by tealdragonoid** [comment]
Hi,

Of note both WeatherUnderground and DarkSky have stopped syncing weather data. The last successful sync for me was April 15th, 9:00 PM CST. I Hope this can be resolved!

**Comment by fliP-13** [comment]
I think it might be related to an expired certificate on https://api.sunrise-sunset.org/, which is used independently from the actual weather forecast provider.

**Comment by mattrossman** [comment]
Thanks for reporting this, and nice to see so many people here! 😅

Is anyone still having this issue? I can successfully fetch weather currently with the Weather Underground provider. It sounds like there was an issue with one of the APIs but it might have been fixed on their end (I forgot to wear my pebble the past couple days, so I guess this went under my radar).

**Comment by lstarritt** [comment]
My Weatherunderground is working properly once again!

**Comment by TomF8COD** [comment]
Hello Matt,
It was still not working yesterday afternoon (I'm in France) but everything is working perfectly this morning. This is my favorite watchface, thanks for your work!
Tom

18 avr. 2022 04:26:58 Matt Rossman ***@***.***>:

**Comment by tuxianerDE** [comment]
Same here. Did resolve itself, probably was related to the certificate issue of the sunrise API, as I don't get a certificate warning anymore and the watchface looks beautiful again :)
