### ISSUE TITLE
Weather Update not working late July 2022

### ISSUE THREAD

**Issue by lstarritt** [mattrossman/forecaswatch2#56]
As title says, weather update is not working. I have attempted Weather Underground and DarkSky, as I still have a DarkSky api key. This issue began presenting about 6pm CT Friday July 22 (Midnight GMT Saturday July 23) across multiple locations, with or without wifi and manual updates.

**Comment by mmckeever23** [comment]
Yes, seems Dark Sky is not working anymore. OpenWeatherMap still works with an API key.

**Comment by lstarritt** [comment]
I don't have an option for openweathermap? I'm using the version from the rebble store, is there a more updated version I am unaware of?

**Comment by mmckeever23** [comment]
Download the most recent version here in GitHub.

**Comment by lstarritt** [comment]
This did indeed work
