### ISSUE TITLE
v1.19.0 weather update failing (late July 2022, number 3) for weather underground & dark sky due to sunset/rise look up error (sunrise-sunset.org)

### ISSUE THREAD

**Issue by clach04** [mattrossman/forecaswatch2#60]
https://github.com/clach04/pebble-forecaswatch2-fcsw2-fcw2/blob/gha-no-make/src/pkjs/weather/provider.js#L29

uses https, this is an insecure connection (today) and on Pebble just hangs.

> The certificate for api.sunrise-sunset.org expired on 7/22/2022.
> Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Discovered in https://github.com/mattrossman/forecaswatch2/issues/57

Workarounds:

* use openweathermap provider
* edit PBW (extractjs) and update url to use http instead of https, replace:

        var urlToday = 'https://api.sunrise-sunset.org/json?formatted=0'

    with:

        var urlToday = 'http://api.sunrise-sunset.org/json?formatted=0'

**Comment by PowerScissor** [comment]
Update:  I created a new API with OpenWeather and I guess it can take up to 2 hours to become active....just now openweather, GPS, version 1.19 does indeed work currently.

Thanks for the help, I would have never figured that out by myself.

**Comment by clach04** [comment]
@PowerScissor please could you do me a favor? Go to https://github.com/clach04/pebble-forecaswatch2-fcsw2-fcw2/actions/runs/2742328294 (scroll down) and download the App.zip, it has a new PBW in it. Assuming GPS is enabled, location override is NOT set (like https://github.com/mattrossman/forecaswatch2/issues/57) your previous providers should now work.

**Comment by PowerScissor** [comment]
Sorry for the delay, work got crazy.

Can confirm that did indeed solve the problem.  Only tested with GPS, as I never manually enter location.

Thanks!

**Comment by clach04** [comment]
Thanks @PowerScissor  I'm in the same boat, thanks for taking the time to test and share feedback!

**Comment by clach04** [comment]
@mattrossman if you have a few mins to review https://github.com/mattrossman/forecaswatch2/pull/62 (super simple change) and merge it, we'll have at least 2 providers up and working 100% with just one remaining that either needs a workaround or https://github.com/mattrossman/forecaswatch2/issues/57 which requires a new (free) key (optionally https://github.com/mattrossman/forecaswatch2/issues/59)

**Comment by mattrossman** [comment]
Thanks for catching this. I think I'll switch to something other than sunrise-sunset for this. I don't like the idea of sending user coordinates over an insecure connection.

I see you mentioned https://github.com/mourner/suncalc in another thread. I like the idea of using an on-device library for this, one less web service to break down the line. I'm going to do a quick comparison of the available packages out there to see what has the smallest footprint.

**Comment by mattrossman** [comment]
Suncalc looks good to me. Pretty small lib and permissive license. Will include this in the next release.
