### ISSUE TITLE
Release newer versions on Rebble app store

### ISSUE THREAD

**Issue by denilsonsa** [mattrossman/forecaswatch2#65]
I can see on GitHub that we have v1.19.0: https://github.com/mattrossman/forecaswatch2/releases

However, on Rebble app store, accessible from the Pebble app itself, it's still 1.14 from almost two years ago: https://apps.rebble.io/en_US/application/5dcdca6ac393f50cf6dbc264

When a new release gets released, it would be great to also have it on the Rebble store, so that it gets automatically updated on our watches.

**Comment by clach04** [comment]
I strongly recommend against publishing V1.19 to apstore and instead waiting for next release.

https://github.com/mattrossman/forecaswatch2/issues?q=is%3Aissue+is%3Aopen++July+2022

**Comment by mattrossman** [comment]
I just got access to the rebble dev portal, so releasing should be easier now. I'll submit v1.20.0 later today.

**Comment by mattrossman** [comment]
v1.20.0 is now published on the Rebble store.

https://apps.rebble.io/en_US/application/5dcdca6ac393f50cf6dbc264
